logging.level.org.springframework.security: INFO
logging.level.org.apache.http.wire: INFO
logging.level.com.orange.clara.cloud.services.sandbox.ElpaasoSandboxServiceApplication: INFO

cloudfoundry:
  apiUrl: https://api.pivotal.io/
  proxyInfo:
    enabled: false
    host:
    port: 0
  credentials:
    userId:
    password:
  trustSelfSignedCerts: false
  org: sandboxes
  space: default-space
server:
  port: 8081
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
security:
  basic.enabled: false
  enable_csrf: true
  require_ssl: true
  sessions: IF_REQUIRED
  oauth2:
    admin.scope: ${SECURITY_OAUTH2_ADMIN_SCOPE:cloud_controller.admin}
    resource:
       jwt:
          keyValue: ${SECURITY_OAUTH2_RESOURCE_JWT_KEY_VALUE:no_key_defined}
endpoints:
  actuator:
    sensitive: true
management:
  security:
    enabled: true
  context-path: /manage
server:
  session:
    timeout: 240
